version: "3.8"
services:
  database:
    container_name: database-ps
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crud
    ports:
      - "5432:5432"
  app:
    container_name: application-ps
    build:
      context: .
    ports:
     - "1323:1323"
    environment:
      - DATABASE_USER=user
      - DATABASE_PASSWORD=pass
      - DATABASE_DB=crud